version: '3.1'
services:
  odrabiamy-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty12345
      POSTGRES_DB: odrabiamy
    ports:
      - 5432:5432
    volumes:
     - ./postgres-data:/var/lib/postgresql/data